source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ScanTouch_Example', :exclusive => true do
  pod "ScanTouch", :path => "../"
end

target 'ScanTouch_Tests', :exclusive => true do
  pod "ScanTouch", :path => "../"

  
end
